const menu = [{
        id: 1,
        title: "Buttermilk Pancakes",
        price: 15,
        category: "Breakfast",
        image: "menu-image/chad-montano-eeqbbemH9-c-unsplash.jpg",
        desc: "Buttermilk Pancakes served with Bananas & Maple.",
        authorLink: "https://unsplash.com/@briewilly?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Chad Montano",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 2,
        title: "Waffles",
        price: 13,
        category: "Breakfast",
        image: "menu-image/chad-montano-o7gFaMBrvE4-unsplash.jpg",
        desc: "Hommade Waffles with yogurt, blueberry, raspberry and black chocolate.",
        authorLink: "https://unsplash.com/@briewilly?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Chad Montano",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 50,
        title: "Pizza Pineapple",
        price: 17.99,
        category: "Lunch",
        image: "menu-image/chad-montano-MqT0asuoIcU-unsplash.jpg",
        desc: "Out special pizza with bazzit pineapples and onion.",
        authorLink: "https://unsplash.com/@briewilly?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Chad Montano",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 51,
        title: "Walnuts Salad",
        price: 17,
        category: "Lunch",
        image: "menu-image/eiliv-sonas-aceron-ZuIDLSz3XLg-unsplash.jpg",
        desc: "Lettuce, olives, purple onion, carrot, feta cheese and walnuts with Sauce.",
        authorLink: "https://unsplash.com/@shootdelicious?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Eiliv-Sonas Aceron",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 52,
        title: "Beef Fillet",
        price: 30,
        category: "Lunch",
        image: "menu-image/chad-montano-M0lUxgLnlfk-unsplash.jpg",
        desc: "Hot & soft Beef Fillet served with grees salad and backed potato's.",
        authorLink: "https://unsplash.com/@briewilly?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Chad Montano",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 3,
        title: "Sandwich with boiled egg",
        price: 15,
        category: "Breakfast",
        image: "menu-image/joseph-gonzalez-fdlZBWIP0aM-unsplash.jpg",
        desc: "Roasted white bread with cucumber mayo and rocket leaves.",
        authorLink: "https://unsplash.com/@miracletwentyone?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Joseph Gonzalez",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 54,
        title: "salmon Fillet",
        price: 21,
        category: "Lunch",
        image: "menu-image/casey-lee-awj7sRviVXo-unsplash.jpg",
        desc: "Salmon fillet with mashed potatoes spinach and teriyaki souce, served with salad.",
        authorLink: "https://unsplash.com/@simplethemes?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Casey Lee",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 4,
        title: "French Toast",
        price: 13,
        category: "Breakfast",
        image: "menu-image/joseph-gonzalez-zcUgjyqEwe8-unsplash.jpg",
        desc: "French toast with blueberries and bananas and honey",
        authorLink: "https://unsplash.com/@miracletwentyone?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Joseph Gonzalez",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },

    {
        id: 55,
        title: "Pasta Pesto",
        price: 16,
        category: "Lunch",
        image: "menu-image/eaters-collective-12eHC6FxPyg-unsplash.jpg",
        desc: "Pasta with pesto and tomatoes, parmesan , and chili",
        authorLink: "https://unsplash.com/@eaterscollective?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Eaters Collective",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },

    {
        id: 56,
        title: "Hamburger",
        price: 23,
        category: "Lunch",
        image: "menu-image/chad-montano--GFCYhoRe48-unsplash.jpg",
        desc: "Medium-well burger with beacon, egg , tomatoes, lettuce, cheder, and cheese",
        authorLink: "https://unsplash.com/@briewilly?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Chad Montano",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },

    {
        id: 100,
        title: "Frozen Yogurt",
        price: 7,
        category: "Specials",
        image: "menu-image/pablo-merchan-montes-MXovqM130UI-unsplash.jpg",
        desc: "Homemade Frozen yogurt with dark Raspberry",
        authorLink: "https://unsplash.com/@pablomerchanm?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Pablo Merchán Montes",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 101,
        title: "Strawberry Muffins",
        price: 6,
        category: "Specials",
        image: "menu-image/deva-williamson-S2jw81lfrG0-unsplash.jpg",
        desc: "Butter muffins with strawberry & vanilla cream",
        authorLink: "https://unsplash.com/@biglaughkitchen?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Deva Williamson",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 102,
        title: "Cheesecake",
        price: 8.5,
        category: "Specials",
        image: "menu-image/kim-daniels-OrkEasJeY74-unsplash.jpg",
        desc: "Butter muffins with strawberry & vanilla cream",
        authorLink: "https://unsplash.com/@kimbroughdaniels?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Kim Daniels ",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 200,
        title: "Coffee",
        price: "5-6",
        category: "Hot-drinks",
        image: "menu-image/nathan-dumlao-pMW4jzELQCw-unsplash.jpg",
        desc: "Cappuccino,Latte, Affogatto, Americano, Black coffee",
        authorLink: "https://unsplash.com/@nate_dumlao?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Nathan Dumlao",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 201,
        title: "Tea",
        price: 5,
        category: "Hot-drinks",
        image: "menu-image/massimo-rinaldi-FmgZ5xzDG-s-unsplash.jpg",
        desc: "Green tea, White tea, Lemon tea, Mint tea, Lemon Grass, Red tea",
        authorLink: "https://unsplash.com/@massimorinaldi27?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Massimo Rinaldi",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 57,
        title: "Pepperoni Pizza",
        price: 17,
        category: "Lunch",
        image: "menu-image/likemeat-CbNAuxSZTFo-unsplash.jpg",
        desc: "Pizza with peperony, bazil, hot peppers and tomatoes. ",
        authorLink: "https://unsplash.com/@likemeat?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "LikeMeat",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 300,
        title: "Bottle of Wine",
        price: 17,
        category: "Cold-drinks",
        image: "menu-image/maksym-kaharlytskyi-3uJt73tr4hI-unsplash.jpg",
        desc: "Ask the waiter for Winery of the Day.",
        authorLink: "https://unsplash.com/@qwitka?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Maksym Kaharlytskyi",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 5,
        title: "Vegetable Salad",
        price: 11,
        category: "Breakfast",
        image: "menu-image/chris-ralston-09HGdZzkP-Q-unsplash.jpg",
        desc: "Salad with Black toasted bread and labane.",
        authorLink: "https://unsplash.com/@thisisralston?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Chris Ralston",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 6,
        title: "Granola",
        price: 11,
        category: "Breakfast",
        image: "menu-image/tetiana-bykovets-T4Q2NX1GP4w-unsplash.jpg",
        desc: "Granola with yogurt and fresh fruit.",
        authorLink: "https://unsplash.com/@tetiana_bykovets?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Tetiana Bykovets",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
    {
        id: 302,
        title: "Fresh Iced Juice",
        price: 6,
        category: "Cold-drinks",
        image: "menu-image/yulia-khlebnikova-yIE7pZUmT_s-unsplash.jpg",
        desc: "Lemonade, Apple, Grapefruit, Orange, Apple mint, Strawberry, Kiwi",
        authorLink: "https://unsplash.com/@khlebnikovayulia?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        authorName: "Yulia Khlebnikova",
        WebsiteLink: "https://unsplash.com/images/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText",
        WebsiteName: "Unsplash",
    },
];